# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13b816f21f2f0025128cf8f70dc6be6462da7e54ef2a63d6595480dd5cfb64a7df4dca095fe0ddc72d677dcea5ae69654fe6ef820802f7ce0b8efa8957db7db9

test:
  secret_key_base: d5a18a67c650bacc2175fbcb0140f0a9123ff1c393d91f469273be1f246af54376f0b734d5a5607f1ec56f99daa2c1181c12db07924bbfaf7239d2300d50d3f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
